spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        initial-size: 1
        min-idle: 1
        max-idle: 20
    jpa:
        database: mysql
        show-sql: true
        hibernate:
          ddl-auto: update
          naming:
            strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
        properties:
           hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect


redis:
  shiro:
    host: 127.0.0.1
    post: 6379
    timeout: 0
    password:

# 集群
# redis:
#      cluster:
#        nodes:
#        max-redirects:
mybatis:
  config-location: classpath:mapper/*.xml


