spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      dbcp2:
        initial-size: 1
        min-idle: 1
        max-idle: 20
    jpa:
        database: mysql
        show-sql: true
        hibernate:
          ddl-auto: update
          naming:
            strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
        properties:
           hibernate:
              dialect: org.hibernate.dialect.MySQL5Dialect


  redis:
    host: 127.0.0.1
    post: 6379
    timeout: 2000
    database: 1

# 集群
# redis:
#      cluster:
#        nodes:
#        timeout : 2000
#        maxIdle : 150
#        minEvictableIdleTimeMillis : 864000000
#        minIdle : 50
#        numTestsPerEvictionRun : 10
#        softMinEvictableIdleTimeMillis : 10
#        testOnBorrow : false
#        testOnReturn : false
#        testWhileIdle : false
#        timeBetweenEvictionRunsMillis : 300000
mybatis:
  config-location: classpath:mapper/*.xml


