spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver


redis:
  shiro:
    host: 127.0.0.1
    post: 6379
    timeout: 0
    password:
mybatis:
  config-location: classpath:mapper/*.xml


